statusbar_format = "%title - %artists"
notify = true
use_nerdfont = true
flip_status_indicators = true
shuffle = true
repeat = "playlist"
cover_max_scale = 2.0
hide_display_names = true

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[notification_format]
title = "%title"
body = "%artists"

[keybindings]
"n" = "next"
"p" = "previous"
"b" = "seek -5000"
"f" = "seek +5000"
"Space" = "playpause"

[theme]
# background = "#303446"
primary = "#cdd6f4"
secondary = "#74c7ec"
title = "#89b4fa"
playing = "#89b4fa"
playing_selected = "#89b4fa"
playing_bg = "#313244"
highlight = "#74c7ec"
highlight_bg = "#181825"
error = "#E78284"
error_bg = "#EEBEBE"
statusbar = "#292C3C"
statusbar_progress = "#89b4fa"
statusbar_bg = "#89b4fa"
cmdline = "#89b4fa"
cmdline_bg = "#181825"

