#! /bin/bash

#define icons for workspaces 1-10
ic=(0 '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰮯' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠' '󰊠')

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | awk '{print $3}'); do 
  export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep -B 4 "focused: yes" | awk 'NR==1{print $3}'); do 
  export f"$num"="$num"
  export fnum=f"$num"
  export mon=$(hyprctl monitors | grep -B 2 "\($num\)" | awk 'NR==1{print $2}')
done

workspaces() {
if [[ ${1:0:9} == "workspace" ]] && [[ ${1:11} != "special" ]]; then #set focused workspace
  unset -v "$fnum" 
  num=${1:11}
  ic[$num]='󰮯'
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:10} == "focusedmon" ]]; then #set focused workspace following monitor focus change
  unset -v "$fnum"
  string=${1:12}
  num=${string##*,}
  ic[$num]='󰮯'
  export mon=${string/,*/}
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:13} == "moveworkspace" ]] && [[ ${1##*,} == "$mon" ]]; then #Set focused workspace following swapactiveworkspace
  unset -v "$fnum"
  string=${1:15}
  num=${string/,*/}
  ic[$num]='󰮯'
  export f"$num"="$num"
  export fnum=f"$num"

elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
  num=${1:17}
  ic[$num]='󰮯'
  export o"$num"="$num"
  export onum=o"$num"

elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
  num=${1:18}
  ic[$num]='󰊠'
  unset -v o"$num"
fi
}
module() {
#output eww widget
  echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
            (box	:class \"works\"	:orientation \"h\" :spacing 5 :space-evenly \"false\" :valign \"center\"	\
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 1\'\" :onrightclick \"hyprctl dispatch workspace 1 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o11$f11\" \"${ic[11]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 2\'\" :onrightclick \"hyprctl dispatch workspace 2 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o12$f12\" \"${ic[12]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 3\'\" :onrightclick \"hyprctl dispatch workspace 3 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o13$f13\" \"${ic[13]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 4\'\" :onrightclick \"hyprctl dispatch workspace 4 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o14$f14\" \"${ic[14]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 5\'\" :onrightclick \"hyprctl dispatch workspace 5 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o15$f15\" \"${ic[15]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 6\'\" :onrightclick \"hyprctl dispatch workspace 6 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o16$f16\" \"${ic[16]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 7\'\" :onrightclick \"hyprctl dispatch workspace 7 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o17$f17\" \"${ic[17]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 8\'\" :onrightclick \"hyprctl dispatch workspace 8 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o18$f18\" \"${ic[18]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 9\'\" :onrightclick \"hyprctl dispatch workspace 9 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o19$f19\" \"${ic[19]}\") \
                (button :onclick \"hyprctl dispatch exec \'~/.local/bin/workspace 10\'\" :onrightclick \"hyprctl dispatch workspace 10 && $HOME/.config/hypr/themes/garden/scripts/default_app\" :class \"1$o20$f20\" \"${ic[20]}\") \
            )\
          )"
}

module $1

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
workspaces "$event"
module
done
